services:
  web:
    depends_on:
      - storage
      - api

    build: ./pet-adoption-frontend 
    ports:
      - "3000:3000" 

    environment:
      - api_url=http://localhost:8000


  storage:
    build: ./multer-server

    ports:
      - "5000:5000"

    env_file:
      - ./multer-server/.env    

    environment:
      - storage_url=http://localhost:5000

  api:
    build: ./pet-adoption-backend
    ports:
      - "5050:5050"

    env_file:
      - ./pet-adoption-backend/.env    

                                          